# Format: https://dart.dev/tools/pub/pubspec

name: workspace

# UNCOMMENT THESE TO PUBLISH TO PUB.
# description: |-
#   A description of the package.
# version: 0.0.0
# repository: https://github,com/matanlurey/package

environment:
  sdk: ^3.7.0

workspace:
  - packages/package

dev_dependencies:
  chore:
    git:
      url: https://github.com/matanlurey/pub.lurey.dev
      path: packages/chore
      ref: 58b4e27d43a12b4cb76a49495d70ad10f78e5ee4
  oath: ^0.4.0
