# Format: https://dart.dev/tools/pub/pubspec
name: package

description: |-
  A description of the package.

short_description: |-
  A package.

environment:
  sdk: ^3.7.0

publish_to: none

resolution: workspace

dependencies:
  meta: ^1.16.0

dev_dependencies:
  checks: ^0.3.0
  test: ^1.25.14
