name: package/package

on:
  # Post-submit.
  push:
    branches: [ main ]

  # Pre-submit.
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/package_package.yaml
      - packages/package/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: dart-lang/setup-dart@v1.6.5
      - run: dart pub get
      - run: ./dev.sh setup --packages packages/package
      - run: ./dev.sh check --packages packages/package
      - run: ./dev.sh generate --no-root --fail-if-changed --packages packages/package
      - run: ./dev.sh test --packages packages/package
